# Generated by Django 4.0.3 on 2022-03-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
